### ISSUE TITLE
After upgrade to version 1.0-beta-5 I cant install gravity forms

### ISSUE THREAD

**Issue by micheldenegri** [gravityforms/gravityformscli#5]
Hello,

After upgrade to version 1.0-beta-5 I cant install gravityforms plugin with this command:
`wp gf install` I have my key with `GF_LICENSE_KEY` constant.

This is the error I'm getting:

```
PHP Fatal error:  Uncaught Error: Class 'GFCommon' not found in path/to/plugins/gravityformscli/includes/class-gf-cli-root.php:103
Stack trace:
#0 [internal function]: GF_CLI_Root->install(Array, Array)
#1 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/bin/wp/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Runner.php(929): WP_CLI\Runner->_run_command()
#7 phar:///usr/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapStat in /path/to/plugins/gravityformscli/includes/class-gf-cli-root.php on line 103
Fatal error: Uncaught Error: Class 'GFCommon' not found in /path/to/plugins/gravityformscli/includes/class-gf-cli-root.php:103
Stack trace:
#0 [internal function]: GF_CLI_Root->install(Array, Array)
#1 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/bin/wp/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Runner.php(929): WP_CLI\Runner->_run_command()
#7 phar:///usr/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapStat in /path/to/plugins/gravityformscli/includes/class-gf-cli-root.php on line 103
```

**Comment by richardW8k** [comment]
This has been fixed in the master branch.
