### ISSUE TITLE
"Class 'GFCommon' not found" when attempting to install plugins from cli plugin

### ISSUE THREAD

**Issue by ErnieAtLYD** [gravityforms/gravityformscli#6]
Hello! Right now I am experiencing the following when trying to install gravityforms via cli script: 

```
$ wp plugin delete gravityforms
Warning: The 'gravityforms' plugin could not be found.
Success: Plugin already deleted.
$ wp plugin delete gravityformscli
Deleted 'gravityformscli' plugin.
Success: Deleted 1 of 1 plugins.
$ wp plugin install gravityformscli --activate
Installing Gravity Forms CLI Add-On (1.0-beta-5)
Downloading install package from https://downloads.wordpress.org/plugin/gravityformscli.zip...
Using cached file '/Users/ernie/.wp-cli/cache/plugin/gravityformscli-1.0-beta-5.zip'...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'gravityformscli'...
Warning: Plugin 'gravityformscli' is already active.
Success: Installed 1 of 1 plugins.
$ wp gf install --key=[OURLICENSEKEY] --activate
Fatal error: Class 'GFCommon' not found in /Users/ernie/Sites/vagrant-local/www/wbu/public_html/wp-content/plugins/gravityformscli/includes/class-gf-cli-root.php on line 103
```

I am experiencing this both locally and when I run a similar version of this on our travis build, where we get the additional stack trace issue:

```
Stack trace:
#0 [internal function]: GF_CLI_Root->install(Array, Array)
#1 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#4 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Runner. in /home/travis/build/wherebyus/wbu-referrals/tmp/wp-content/plugins/gravityformscli/includes/class-gf-cli-root.php on line 103
Fatal error: Uncaught Error: Class 'GFCommon' not found in /home/travis/build/wherebyus/wbu-referrals/tmp/wp-content/plugins/gravityformscli/includes/class-gf-cli-root.php:103
Stack trace:
#0 [internal function]: GF_CLI_Root->install(Array, Array)
#1 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#4 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///home/travis/build/wherebyus/wbu-referrals/tmp/wp-cli.phar/php/WP_CLI/Runner. in /home/travis/build/wherebyus/wbu-referrals/tmp/wp-content/plugins/gravityformscli/includes/class-gf-cli-root.php on line 103
Error: Gravity Forms is not installed. Use the "wp gf install" command to install Gravity Forms.
```

Any help would be appreciated, as I'm not sure what to do next. Thanks so much!

**Comment by richardW8k** [comment]
This issue has been fixed in the master branch.

**Comment by a-morales** [comment]
@richardW8k creating a new release and updating the version on the official wordpress plugins repository should resolve future issues from being created. From experience most people don't install plugins from git repositories, and instead go through wordpress's plugin dashboard.
